=== sb-ncbr/SecStrAnnotator2/scripts/funpdbe_validator/data/funpdbe_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "https://gitlab.ebi.ac.uk/pdbe-kb/funpdbe/funpdbe-schema/raw/master/funpdbe_schema.json",
  "title": "funpdbe_schema",
  "type": "object",
  "properties": {
    "data_resource": {
      "type": "string",
      "description": "Name of the database or software"
    },
    "resource_version": {
      "type": "string",
      "description": "Version of the resource"
    },
    "software_version": {
      "type": "string",
      "description": "Version of the software used"
    },
    "resource_entry_url": {
      "type": "string",
      "description": "URL linking to the entry at the partner resource"
    },
    "release_date": {
      "type": "string",
      "description": "Release date of the annotation",
      "pattern": "^[0-3]*[0-9]/[0-1]*[0-9]/[1-2][0-9]{3}$"
    },
    "pdb_id": {
      "type": "string",
      "description": "PDB identifier",
      "pattern": "^[1-9][a-zA-Z0-9]{3}$"
    },
    "additional_entry_annotations": {
      "type": "object",
      "description": "Additional entry-level annotations",
      "additionalProperties": true
    },
    "chains": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "chain_label": {
            "type": "string",
            "description": "PDB chain identifier"
          },
          "additional_chain_annotations": {
            "type": "object",
            "description": "Additional chain-level annotations",
            "additionalProperties": true
          },
          "residues": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "pdb_res_label": {
                  "type": "string",
                  "description": "Residue index from the related PDB entry"
                },
                "aa_type": {
                  "type": "string",
                  "description": "Three-letter amino acid code",
                  "pattern": "^[A-Za-z0-9]+$"
                },
                "additional_residue_annotations": {
                  "type": "object",
                  "description": "Additional residue-level annotations",
                  "additionalProperties": true
                },
                "site_data": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "site_id_ref": {
                        "type": "integer",
                        "description": "Reference to site_id"
                      },
                      "raw_score": {
                        "type": "number",
                        "description": "Raw calculated score"
                      },
                      "confidence_score": {
                        "type": "number",
                        "description": "Confidence level of the annotation (0-1, except if the method justifies otherwise)",
                        "minimum": 0.0
                      },
                      "confidence_classification": {
                        "type": "string",
                        "description": "Confidence classification of the residue",
                        "enum": [
                          "high",
                          "medium",
                          "low",
                          "null",
                          "curated"
                        ]
                      },
                      "aa_variant": {
                        "type": "string",
                        "description": "Three-letter amino acid code of variant/mutant",
                        "pattern": "^[A-Za-z0-9]+$"
                      }
                    },
                    "required": [
                      "site_id_ref",
                      "confidence_classification"
                    ],
                    "additionalProperties": false
                  },
                  "minItems": 1,
                  "uniqueItems": true
                }
              },
              "required": [
                "pdb_res_label",
                "aa_type",
                "site_data"
              ],
              "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
          }
        },
        "required": [
          "chain_label",
          "residues"
        ],
        "additionalProperties": false
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "sites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "site_id": {
            "type": "integer",
            "description": "Site identifier"
          },
          "label": {
            "type": "string",
            "description": "Site label"
          },
          "source_database": {
            "type": "string",
            "description": "Name of the source database"
          },
          "source_accession": {
            "type": "string",
            "description": "Accession identifier"
          },
          "source_release_date": {
            "type": "string",
            "description": "Date of acquiring data from source",
            "pattern": "^[0-3]*[0-9]/[0-1]*[0-9]/[1-2][0-9]{3}$"
          },
          "additional_site_annotations": {
            "type": "object",
            "description": "Additional site-level annotations",
            "additionalProperties": true
          }
        },
        "required": [
          "site_id",
          "label"
        ],
        "additionalProperties": false
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "evidence_code_ontology": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "eco_term": {
            "type": "string",
            "description": "Evidence Code Ontology (ECO) term - http://www.evidenceontology.org/"
          },
          "eco_code": {
            "type": "string",
            "description": "Evidence Code Ontology (ECO) code - http://www.evidenceontology.org/",
            "pattern": "^ECO_[0-9]{7}$"
          }
        },
        "required": [
          "eco_code"
        ],
        "additionalProperties": false
      },
      "minItems": 1,
      "uniqueItems": true
    }
  },
  "required": [
    "data_resource",
    "pdb_id",
    "chains",
    "evidence_code_ontology",
    "sites"
  ],
  "additionalProperties": false
}

=== sb-ncbr/SecStrAnnotator2/scripts/funpdbe_validator/data/test_data.json
{
  "data_resource": "ProKinO",
  "resource_version": "2.0",
  "software_version": "2.0",
  "resource_entry_url": "http://vulcan.cs.uga.edu/prokino/",
  "release_date": "10/02/2017",
  "pdb_id": "2gs6",
  "chains": [
    {
      "residues": [
        {
          "pdb_res_label": "811",
          "aa_type": "HIS",
          "site_data": [
            {
              "confidence_score": 1,
              "site_id_ref": 1,
              "confidence_classification": "high",
              "raw_score": 1
            }
          ]
        },
        {
          "pdb_res_label": "812",
          "aa_type": "ARG",
          "site_data": [
            {
              "confidence_score": 1,
              "site_id_ref": 2,
              "confidence_classification": "high",
              "raw_score": 1
            }
          ]
        },
        {
          "pdb_res_label": "813",
          "aa_type": "ASP",
          "site_data": [
            {
              "confidence_score": 1,
              "site_id_ref": 2,
              "confidence_classification": "high",
              "raw_score": 1
            }
          ]
        }
      ],
      "chain_label": "A"
    }
  ],
  "sites": [
    {
      "site_id": 1,
      "label": "HRD motif"
    },
    {
      "site_id": 2,
      "label": "HRD motif"
    },
    {
      "site_id": 3,
      "label": "HRD motif"
    }
  ],
  "evidence_code_ontology": [
    {
      "eco_term": "computational combinatorial evidence",
      "eco_code": "ECO_0000246"
    }
  ]
}

=== sb-ncbr/SecStrAnnotator2/scripts/funpdbe_validator/data/test_data_multichain.json
{
  "data_resource": "ProKinO",
  "resource_version": "2.0",
  "software_version": "2.0",
  "resource_entry_url": "http://vulcan.cs.uga.edu/prokino/",
  "release_date": "10/02/2017",
  "pdb_id": "1yj9",
  "chains": [
    {
      "residues": [
        {
          "pdb_res_label": "0",
          "aa_type": "MET",
          "site_data": [
            {
              "confidence_score": 1,
              "site_id_ref": 1,
              "confidence_classification": "high",
              "raw_score": 1
            }
          ]
        },
        {
          "pdb_res_label": "1",
          "aa_type": "GLY",
          "site_data": [
            {
              "confidence_score": 1,
              "site_id_ref": 2,
              "confidence_classification": "high",
              "raw_score": 1
            }
          ]
        },
        {
          "pdb_res_label": "2",
          "aa_type": "ARG",
          "site_data": [
            {
              "confidence_score": 1,
              "site_id_ref": 2,
              "confidence_classification": "high",
              "raw_score": 1
            }
          ]
        }
      ],
      "chain_label": "A"
    }
  ],
  "sites": [
    {
      "site_id": 1,
      "label": "HRD motif"
    },
    {
      "site_id": 2,
      "label": "HRD motif"
    },
    {
      "site_id": 3,
      "label": "HRD motif"
    }
  ],
  "evidence_code_ontology": [
    {
      "eco_term": "computational combinatorial evidence",
      "eco_code": "ECO_0000246"
    }
  ]
}
